anarchy-ai/LLM-VM

README.md

Added documentation for completion/ module

---

src/llm_vm/completion/config.json
src/llm_vm/completion/models.py
src/llm_vm/completion/optimize.py
src/llm_vm/onsite_llm.py

Made changes that allows the api to use any models, tested with hugging face models and got completion to work.
All LLM options have been moved to onsite_llm.py, and models.py reads the config.json and then selects the big and small models.

Config for big and small models

---

.gitignore
pyproject.toml

altered pyproject.toml file to allow poetry install to work
Adjusted gitignore to account for poetry file created.

adjusted pyproject.toml configuration to start poetry install

---

integration_tests/src/llm_vm/server/main_tests.py
src/llm_vm/onsite_llm.py
src/llm_vm/server/main.py
src/llm_vm/server/routes.py

Added documentation for main.py and onsite_llm.py

Added some documentation to code

---

README.md

@mmirman @abhigya-sodani  @AryPathania @ajn2004 thoughts?

better top of line blurbs

---

README.md
quickstart.py
src/llm_vm/client.py
src/llm_vm/completion/models.py
src/llm_vm/onsite_llm.py

Client.py acts as a quickstart entry point to optimize.complete()
README adjusted to reflect that a bit

working client entry point

---

quickstart.py
src/llm_vm/client.py
src/llm_vm/completion/data_synthesis.py
src/llm_vm/completion/optimize.py
src/llm_vm/completion/test_data_synthesis.py
src/llm_vm/onsite_llm.py

Issues with data synthesis fixed. I made it such that to run data synthesis we had to provide an openai key, as GPT is the only LLM I tested that successfully generated data.

Data synthesis fixes

---

quickstart.py
quickstart_finetune.py
src/llm_vm/client.py
src/llm_vm/onsite_llm.py

I believe this adds pythia functionality for our current branch. There were changes to the quickstart files for testing.
Completion and finetuning work on my machine with this model, using chat_gpt as a teacher.

added support for pythia 70M model fine-tuning saves model

---

src/llm_vm/onsite_llm.py

issue #69 adds Bert to onsite llms
this PR also modifies each class for the local LLM models so that it inherits functionality from the Base LLM class

added inheritance for all huggingface models

---

README.md

edits to readme.md

---

quickstart_finetune.py
src/llm_vm/client.py
src/llm_vm/config.py
src/llm_vm/onsite_llm.py

fine tuning hang!
also place the default models list in a location where it'll be easier to keep up to date
@ajn2004  this fixes the reporting issue i found wrt WandB prompt mid execution, and it also moves the config map into a location where it can be kept up to date with respect to supported models
@dorkitude  any style guidance or opinions welcome

suppress reporting, the default config of "enable all" was making

---

pyproject.toml

minor change adding a dependency required for server launch

added flask_cors to the project file

---

src/llm_vm/config.py

look for settings TOML files in curent working directory

---

.gitignore
README.md

Some English grammar fixes. Please see the changes below.
Merge #121 before this as it is a separate change.

Readme changes

---

SERVER_API.md

https://github.com/anarchy-ai/LLM-VM/issues/170
https://github.com/anarchy-ai/LLM-VM/issues/146

Minor documentation changes

---

examples/eval_finetuned.py
examples/quickstart.py
examples/quickstart_REBEL.py
examples/quickstart_finetune.py
examples/quickstart_finetune_load.py
examples/quickstart_guided.py

move example files

---

output.txt
src/llm_vm/server/main.py
src/llm_vm/utils/ram.py

RAM Usage log

---

src/llm_vm/config.py

Remove parse arguments

---

quickstart_interface.py

Just the basic things like passing the parameters to the models. Will have to implement the selection of models and other stuffs that was discussed before.
Closes #115

Feature/ajay vishnu/localhost control panel

---

examples/quickstart_quantized_llama.py
pyproject.toml
src/llm_vm/onsite_llm.py

Can test by modifying quickstart.py to be the following:
`client = Client(big_model='quantized-llama', small_model='quantized-llama')`

feat: add support for quantized-llama using GGML

---

src/llm_vm/client.py
src/llm_vm/completion/optimize.py
src/llm_vm/onsite_llm.py

Renamed many classes and fixed comments for __private_key_value_models_map.

 Rename onsite_llm classes to follow PEP 8 standard Closes #195

---

pyproject.toml
src/llm_vm/onsite_llm.py

close #222
close #223 
close #97

feat: added lora/qlora support

---

pyproject.toml
src/llm_vm/onsite_llm.py

Revert "feat: added lora/qlora support"

---

src/llm_vm/onsite_llm.py

fixed onsite llm bug

---

src/llm_vm/onsite_llm.py

feat: auto device selection, cpu, gpu, multi-gpu

---

src/llm_vm/completion/data_synthesis.py

consolidate common logic in DataSynthesis.generate_example

---

src/llm_vm/client.py

closes #287 
cc: @VictorOdede @cartazio

fix default small model assignment in `client.py`

---

src/llm_vm/onsite_llm.py

hello you all.
I just noticed that my last pr was merged. it was missing this change.
my apologies -- I was expecting a comment first before the pr was merged.
but yea this takes care of the `chat_gpt` model from this issue #165. In my last PR I handled `gpt`. thanks

add small_model_filename

---

src/llm_vm/onsite_llm.py

Removed SmallLocalOpenLlama

---

model_uri_tables.md

Fixed doc with incorrect parameters

Fixed model uri table

---

src/llm_vm/onsite_llm.py

fix finetune bug

---

python3
src/llm_vm/client.py

Simplifies Inference without needing a change in documentation until architecture is overhauled. Addresses issue #264

Simple Inference 

---

src/llm_vm/onsite_llm.py

Add ctransformers base class

---

src/llm_vm/onsite_llm.py

added lora finetune

---

src/llm_vm/onsite_llm.py

Added model class for OpenAI's GPT-4 model and did not apply Prettier. This PR is a follow up for the closed https://github.com/anarchy-ai/LLM-VM/pull/317.

Added class for openAI's gpt-4 model

---

src/llm_vm/config.py

Closes https://github.com/anarchy-ai/LLM-VM/issues/306

fix config bug

---

src/llm_vm/completion/data_synthesis.py
src/llm_vm/onsite_llm.py

closes #289 
@VictorOdede @cartazio could you take a look at it, looking forward to any comments!

support all big models for generating examples during finetuning

---

README.md

reference #318 
cc: @cartazio @VictorOdede

update readme examples `llama` -> `llama2`

---

pyproject.toml

closes #326
cc: @VictorOdede @cartazio

add peft and trl to dependencies

---

CONTRIBUTING.md
README.md
SERVER_API.md

Closes https://github.com/anarchy-ai/LLM-VM/issues/145

Fix Docs Grammar

---

src/llm_vm/completion/data_synthesis.py
src/llm_vm/onsite_llm.py

Revert "support all big models for generating examples during finetuning"

---

pyproject.toml

Closes https://github.com/anarchy-ai/LLM-VM/issues/351

add missing requirements

---

README.md

So, I tried to install LLM-VM the way the README said so -- i.e., 
```
./setup.sh
```
But I got the error:
```
* Checking OS..
bash: ./bin/setup_linux.sh: No such file or directory
```
So this fix makes it clear in case someone else gets the same error.

fix bug and make it clear

---

src/llm_vm/completion/optimize.py

Attempt to fix https://github.com/anarchy-ai/LLM-VM/issues/340

fix bug that caused steamlit to not work

---

setup.sh

I have updated the setup.sh file so that it will work for both Linux and Mac.
Issue Addressed: #324
@VictorOdede can you please look into it and let me know if any changes required ..!!

Added Support For Linux along with Mac

---

src/llm_vm/client.py
src/llm_vm/onsite_llm.py

this fixes #328.
I was able to run the source of error:
```python
>>> from client import Client 
>>> client = Client(big_model='bloom')
`bigscience/bloom-560m` loaded on cuda:0.
`EleutherAI/pythia-70m-deduped` loaded on cuda:0.
Using model: bloom
>>> re = client.complete(prompt = 'What is Anarchy?', context='')
Running with an empty context
>>> re
{'completion': '”\nThe question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The question is not new. The …
```

Assign temp var to open ai models

---

src/llm_vm/onsite_llm.py

Closes https://github.com/anarchy-ai/LLM-VM/issues/190

Implement Code Llama in LLM-VM

---

src/llm_vm/vector_db.py

Weaviate integration

---

eval_finetuned.py
examples/quickstart.py
src/llm_vm/agents/FLAT/agent_helper/bothandler.py
src/llm_vm/agents/FLAT/agent_helper/requests/call_open_ai.py
src/llm_vm/agents/FLAT/models/helpers/check_model_status.py
src/llm_vm/agents/FLAT/models/helpers/delete_model.py
src/llm_vm/agents/FLAT/models/helpers/upload_model.py
src/llm_vm/agents/REBEL/bothandler.py
src/llm_vm/agents/REBEL/utils.py
src/llm_vm/completion/data_synthesis.py
src/llm_vm/completion/optimize.py
src/llm_vm/onsite_llm.py
tests/test_optimize.py

openai api migration

---

pyproject.toml
src/llm_vm/completion/data_synthesis.py
src/llm_vm/vector_db.py

version fixes

---

src/llm_vm/client.py
src/llm_vm/onsite_llm.py
tests/test_change_dtype.py

(feat): Ability to change model dtype
